import type {Metadata} from "next";
import React, {ReactNode} from "react";
import {cookies} from "next/headers";
import Menu from "@/app/components/menu/Menu";
import {IUserWithToken} from "@/app/models/user-with-token/IUserWithToken";

export const metadata: Metadata = {
    title: "Next Assessment",
    description: "Generated by create next app",
};

type Props = {
    children: ReactNode;
}

export default async function RootLayout({children}: Props) {
    const cookieStore = await cookies();
    const userDataCookie = cookieStore.get('userData')?.value;

    const user: IUserWithToken = userDataCookie ? JSON.parse(userDataCookie) : null;

    return (
        <html lang="en">
        <body>
        {user && <Menu user={user} />}
        {children}
        </body>
        </html>
    );
}
