import type {Metadata} from "next";
import React, {ReactNode} from "react";
import {ClientProvider} from "@/app/components/ClientProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
        <body>
        <ClientProvider>
            {children}
        </ClientProvider>

        </body>
        </html>
    );
}
